-- Create glossary table for terms and definitions with tooltip support
CREATE TABLE glossary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term TEXT NOT NULL UNIQUE,
  slug VARCHAR(255) NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9_-]{2,}$'),
  definition TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Add updated_at trigger using existing function
CREATE TRIGGER update_glossary_updated_at
  BEFORE UPDATE ON glossary
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create indexes for better query performance
CREATE INDEX idx_glossary_term ON glossary (term);
CREATE INDEX idx_glossary_slug ON glossary (slug);

-- Enable Row Level Security
ALTER TABLE glossary ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Allow read access for all authenticated users
CREATE POLICY "Allow read access for authenticated users"
  ON glossary
  FOR SELECT
  TO authenticated
  USING (true);

-- RLS Policy: Allow all operations for admins and authors
CREATE POLICY "Enable all access for admins and authors"
  ON glossary
  FOR ALL
  TO authenticated
  USING (is_admin() OR is_author())
  WITH CHECK (is_admin() OR is_author());